// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Mock data for development
const mockPosts = [
  {
    id: '1',
    title: 'Getting Started with React Hooks',
    slug: 'getting-started-react-hooks',
    content: 'React Hooks revolutionized how we write React components. In this article, we explore the basics of hooks and how they can simplify your code.',
    excerpt: 'Learn the fundamentals of React Hooks',
    status: 'published' as const,
    featured_image_url: 'https://images.unsplash.com/photo-1633356122544-f134324ef6db?w=800',
    meta_description: 'A comprehensive guide to React Hooks',
    meta_keywords: ['react', 'hooks', 'javascript'],
    og_title: 'React Hooks Guide',
    og_description: 'Learn React Hooks',
    og_image_url: 'https://images.unsplash.com/photo-1633356122544-f134324ef6db?w=800',
    canonical_url: '/articles/getting-started-react-hooks',
    robots_meta: 'index,follow',
    author_id: null,
    published_at: new Date('2024-01-15').toISOString(),
    created_at: new Date('2024-01-15').toISOString(),
    updated_at: new Date('2024-01-15').toISOString()
  },
  {
    id: '2',
    title: 'TypeScript Best Practices',
    slug: 'typescript-best-practices',
    content: 'TypeScript has become essential in modern development. This guide covers best practices for writing maintainable TypeScript code.',
    excerpt: 'Master TypeScript with industry-standard practices',
    status: 'published' as const,
    featured_image_url: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800',
    meta_description: 'TypeScript best practices guide',
    meta_keywords: ['typescript', 'javascript', 'development'],
    og_title: 'TypeScript Best Practices',
    og_description: 'Learn TypeScript best practices',
    og_image_url: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800',
    canonical_url: '/articles/typescript-best-practices',
    robots_meta: 'index,follow',
    author_id: null,
    published_at: new Date('2024-02-20').toISOString(),
    created_at: new Date('2024-02-20').toISOString(),
    updated_at: new Date('2024-02-20').toISOString()
  },
  {
    id: '3',
    title: 'Building Scalable APIs',
    slug: 'building-scalable-apis',
    content: 'Learn how to design and build APIs that can handle millions of requests. We cover caching, load balancing, and database optimization.',
    excerpt: 'Design APIs that scale with your business',
    status: 'published' as const,
    featured_image_url: 'https://images.unsplash.com/photo-1515522570552-f3acc3f8068e?w=800',
    meta_description: 'Guide to building scalable APIs',
    meta_keywords: ['api', 'backend', 'scalability'],
    og_title: 'Scalable APIs Guide',
    og_description: 'Learn to build scalable APIs',
    og_image_url: 'https://images.unsplash.com/photo-1515522570552-f3acc3f8068e?w=800',
    canonical_url: '/articles/building-scalable-apis',
    robots_meta: 'index,follow',
    author_id: null,
    published_at: new Date('2024-03-10').toISOString(),
    created_at: new Date('2024-03-10').toISOString(),
    updated_at: new Date('2024-03-10').toISOString()
  }
];

const mockCategories = [
  { id: '1', name: 'Technology', slug: 'technology', description: 'Tech articles', color: '#3B82F6', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: '2', name: 'Programming', slug: 'programming', description: 'Programming guides', color: '#8B5CF6', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: '3', name: 'Career', slug: 'career', description: 'Career advice', color: '#F59E0B', created_at: new Date().toISOString(), updated_at: new Date().toISOString() }
];

// Create a mock Supabase client
class MockSupabaseClient {
  private authState = {
    session: null as any,
    user: null as any
  };

  auth = {
    onAuthStateChange: (callback: any) => {
      return { data: { subscription: { unsubscribe: () => {} } } };
    },
    getSession: async () => {
      return { data: { session: this.authState.session } };
    },
    signUp: async (credentials: any) => {
      return { error: null, data: null };
    },
    signInWithPassword: async (credentials: any) => {
      return { error: null, data: null };
    },
    signOut: async () => {
      return { error: null };
    }
  };

  from(table: string) {
    return {
      select: (query?: string) => {
        return {
          eq: (field: string, value: any) => {
            return {
              order: (field: string, options?: any) => {
                return {
                  limit: (count: number) => {
                    return {
                      then: (callback: any) => {
                        const getData = async () => {
                          let data = [];
                          if (table === 'posts') {
                            data = mockPosts.filter(p => p[field] === value);
                          } else if (table === 'categories') {
                            data = mockCategories.filter(c => c[field] === value);
                          }
                          return { data, error: null };
                        };
                        return getData().then(result => callback(result));
                      }
                    };
                  },
                  then: (callback: any) => {
                    const getData = async () => {
                      let data = [];
                      if (table === 'posts') {
                        data = mockPosts.filter(p => p[field] === value);
                      } else if (table === 'categories') {
                        data = mockCategories.filter(c => c[field] === value);
                      }
                      return { data, error: null };
                    };
                    return getData().then(result => callback(result));
                  }
                };
              },
              then: (callback: any) => {
                const getData = async () => {
                  let data = [];
                  if (table === 'posts') {
                    data = mockPosts.filter(p => p[field] === value);
                  } else if (table === 'categories') {
                    data = mockCategories.filter(c => c[field] === value);
                  }
                  return { data, error: null };
                };
                return getData().then(result => callback(result));
              }
            };
          },
          order: (field: string, options?: any) => {
            return {
              limit: (count: number) => {
                return {
                  then: (callback: any) => {
                    const getData = async () => {
                      let data: any[] = [];
                      if (table === 'posts') {
                        data = mockPosts.slice(0, count);
                      } else if (table === 'categories') {
                        data = mockCategories.slice(0, count);
                      }
                      // Add post_categories relation
                      if (table === 'posts' && query?.includes('posts_categories')) {
                        data = data.map(post => ({
                          ...post,
                          posts_categories: [
                            { categories: mockCategories[0] },
                            { categories: mockCategories[1] }
                          ]
                        }));
                      }
                      return { data, error: null };
                    };
                    return getData().then(result => callback(result));
                  }
                };
              },
              then: (callback: any) => {
                const getData = async () => {
                  let data: any[] = [];
                  if (table === 'posts') {
                    data = mockPosts;
                  } else if (table === 'categories') {
                    data = mockCategories;
                  }
                  // Add post_categories relation
                  if (table === 'posts' && query?.includes('posts_categories')) {
                    data = data.map(post => ({
                      ...post,
                      posts_categories: [
                        { categories: mockCategories[0] },
                        { categories: mockCategories[1] }
                      ]
                    }));
                  }
                  return { data, error: null };
                };
                return getData().then(result => callback(result));
              }
            };
          },
          then: (callback: any) => {
            const getData = async () => {
              let data: any[] = [];
              if (table === 'posts') {
                data = mockPosts;
              } else if (table === 'categories') {
                data = mockCategories;
              }
              // Add post_categories relation
              if (table === 'posts' && query?.includes('posts_categories')) {
                data = data.map(post => ({
                  ...post,
                  posts_categories: [
                    { categories: mockCategories[0] },
                    { categories: mockCategories[1] }
                  ]
                }));
              }
              return { data, error: null };
            };
            return getData().then(result => callback(result));
          }
        };
      },
      insert: async (data: any) => {
        return { error: null, data: null };
      },
      update: async (data: any) => {
        return { error: null };
      },
      delete: async () => {
        return { error: null };
      }
    };
  }
}

// Use mock client instead of real one
let supabaseClient: any;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.log('Using mock Supabase client for development');
  supabaseClient = new MockSupabaseClient();
} else {
  supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = supabaseClient;